### ISSUE TITLE
Spurious DirectoryNotEmptyException thrown from Files.copy

### ISSUE THREAD

**Issue by Fentonator** [marschall/memoryfilesystem#102]
Attempting to do a Files.copy(Path, Path, CopyOption...) where the target path does not exist (but its immediate parent does, using the REPLACE_EXISITNG, COPY_ATTRIBUTES, and NOFOLLOW_LINKS options, with both the source and target paths living on an instance returned from MemoryFileSystemBuilder.newEmpty().build(), the following exception is thrown. Apologies for the redaction, if it would help I will attempt to construct a test stub that replicates this.
````
    java.nio.file.DirectoryNotEmptyException: [redacted absolute path for target]
        at com.github.marschall.memoryfilesystem/com.github.marschall.memoryfilesystem.MemoryDirectory.checkEmpty(MemoryDirectory.java:81)
        at com.github.marschall.memoryfilesystem/com.github.marschall.memoryfilesystem.MemoryFileSystem.copyEntry(MemoryFileSystem.java:1281)
        at com.github.marschall.memoryfilesystem/com.github.marschall.memoryfilesystem.MemoryFileSystem.handleTwoPathOperation(MemoryFileSystem.java:1392)
        at com.github.marschall.memoryfilesystem/com.github.marschall.memoryfilesystem.MemoryFileSystem$14$1.value(MemoryFileSystem.java:883)
        at com.github.marschall.memoryfilesystem/com.github.marschall.memoryfilesystem.MemoryFileSystem$14$1.value(MemoryFileSystem.java:879)
        at com.github.marschall.memoryfilesystem/com.github.marschall.memoryfilesystem.MemoryFileSystem$13.value(MemoryFileSystem.java:763)
        at com.github.marschall.memoryfilesystem/com.github.marschall.memoryfilesystem.MemoryFileSystem.withLockDo(MemoryFileSystem.java:816)
        at com.github.marschall.memoryfilesystem/com.github.marschall.memoryfilesystem.MemoryFileSystem.withWriteLockOnLastDo(MemoryFileSystem.java:756)
        at com.github.marschall.memoryfilesystem/com.github.marschall.memoryfilesystem.MemoryFileSystem.withWriteLockOnLastDo(MemoryFileSystem.java:752)
        at com.github.marschall.memoryfilesystem/com.github.marschall.memoryfilesystem.MemoryFileSystem.access$400(MemoryFileSystem.java:64)
        at com.github.marschall.memoryfilesystem/com.github.marschall.memoryfilesystem.MemoryFileSystem$14.value(MemoryFileSystem.java:879)
        at com.github.marschall.memoryfilesystem/com.github.marschall.memoryfilesystem.MemoryFileSystem$14.value(MemoryFileSystem.java:875)
        at com.github.marschall.memoryfilesystem/com.github.marschall.memoryfilesystem.MemoryFileSystem$13.value(MemoryFileSystem.java:763)
        at com.github.marschall.memoryfilesystem/com.github.marschall.memoryfilesystem.MemoryFileSystem.withLockDo(MemoryFileSystem.java:816)
        at com.github.marschall.memoryfilesystem/com.github.marschall.memoryfilesystem.MemoryFileSystem.withWriteLockOnLastDo(MemoryFileSystem.java:756)
        at com.github.marschall.memoryfilesystem/com.github.marschall.memoryfilesystem.MemoryFileSystem.withWriteLockOnLastDo(MemoryFileSystem.java:752)
        at com.github.marschall.memoryfilesystem/com.github.marschall.memoryfilesystem.MemoryFileSystem.copyOrMove(MemoryFileSystem.java:875)
        at com.github.marschall.memoryfilesystem/com.github.marschall.memoryfilesystem.MemoryFileSystemProvider.copyOrMove(MemoryFileSystemProvider.java:341)
        at com.github.marschall.memoryfilesystem/com.github.marschall.memoryfilesystem.MemoryFileSystemProvider.copy(MemoryFileSystemProvider.java:326)
        at java.base/java.nio.file.Files.copy(Files.java:1287)
[ … redacted … ]
````

Redacted portion of the stack is just a simple Files.walkFileTree + SimpleFileVisitor implementation, nothing particularly special.

**Comment by Fentonator** [comment]
Copying a directory, with both the source and target on the same filesystem. After a bit of experimentation, it looks like it only happens if there is at least one entry in the source directory.

Expected behavior: it should copy the directory itself (not any contents).

Justification: while the JavaDoc could be clearer, the official tutorial page at https://docs.oracle.com/javase/tutorial/essential/io/copy.html does specifically say:
> Directories can be copied. However, files inside the directory are not copied, so the new directory is empty even when the original directory contains files.

A quick snippet that demonstrates the problem:
````
package demo;

import static java.nio.file.StandardCopyOption.*;

import java.io.IOException;
import java.nio.file.*;

import com.github.marschall.memoryfilesystem.MemoryFileSystemBuilder;

/**
 * Minimal example of Files.copy throwing DirectoryNotEmptyException when
 * copying to a non-existent target.
 */
public class CopyThrowsDirectNotEmptyExample {
    
    public static void main(String[] args) throws IOException {
	try (FileSystem memFS = MemoryFileSystemBuilder.newEmpty().build()) {
	    Path baseDir = Files.createDirectory(memFS.getPath("/anywhere"));
	    Path sourceDir = Files.createDirectory(baseDir.resolve("somewhere"));
	    Path targetDir = baseDir.resolve("nowhere"); // *Not* created
	    
	    Files.createFile(sourceDir.resolve("a_file")); // Key to triggering
	    
	    Files.copy(sourceDir, targetDir, COPY_ATTRIBUTES, REPLACE_EXISTING);
	}
    }
}
````

**Comment by marschall** [comment]
I just release 1.2.2. It may take a few hours before it shows up in Maven Central.

**Comment by Fentonator** [comment]
Looks like the fix works great, thanks.
