### ISSUE TITLE
Files.getFileAttributeView throws UnsupportedOperationException

### ISSUE THREAD

**Issue by io7m** [marschall/memoryfilesystem#55]
Hello.

The documentation for `Files.getFileAttributeView` states that the method returns `null` for unsupported views:

http://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#getFileAttributeView%28java.nio.file.Path,%20java.lang.Class,%20java.nio.file.LinkOption...%29

So, if I create a memory filesystem and don't specify a `PosixFileAttributeView` to the builder, I would expect the above method to return `null` if I attempt:

```
    final PosixFileAttributeView posix_view = Files.getFileAttributeView(
      root, PosixFileAttributeView.class, LinkOption.NOFOLLOW_LINKS);
```

However, I get `UnsupportedOperationException` instead. This makes it somewhat less than useful for checking that code properly handles non-posix filesystems during testing.

```
java.lang.UnsupportedOperationException: file attribute viewinterface java.nio.file.attribute.PosixFileAttributeView not supported
	at com.github.marschall.memoryfilesystem.MemoryEntry.getFileAttributeView(MemoryEntry.java:256)
	at com.github.marschall.memoryfilesystem.MemoryFileSystem$8.value(MemoryFileSystem.java:633)
	at com.github.marschall.memoryfilesystem.MemoryFileSystem$8.value(MemoryFileSystem.java:629)
	at com.github.marschall.memoryfilesystem.MemoryFileSystem.withLockDo(MemoryFileSystem.java:766)
	at com.github.marschall.memoryfilesystem.MemoryFileSystem.withReadLockDo(MemoryFileSystem.java:725)
	at com.github.marschall.memoryfilesystem.MemoryFileSystem.accessFile(MemoryFileSystem.java:675)
	at com.github.marschall.memoryfilesystem.MemoryFileSystem.accessFileReading(MemoryFileSystem.java:663)
	at com.github.marschall.memoryfilesystem.MemoryFileSystem.getFileAttributeView(MemoryFileSystem.java:629)
	at com.github.marschall.memoryfilesystem.MemoryFileSystem$LazyFileAttributeView.getView(MemoryFileSystem.java:1415)
	at com.github.marschall.memoryfilesystem.MemoryFileSystem$LazyFileAttributeView.invoke(MemoryFileSystem.java:1403)
```

**Comment by marschall** [comment]
I just release 0.7.1. The sync to Maven Central may take a few hours.

**Comment by io7m** [comment]
Nice, thanks!
