### ISSUE TITLE
Error when setting umask with 

### ISSUE THREAD

**Issue by natansil** [marschall/memoryfilesystem#98]
when setting umask with `owner write access` an exception is thrown:

```
  val umask = util.EnumSet.of(
    PosixFilePermission.OWNER_WRITE,
    PosixFilePermission.OWNER_READ,
    PosixFilePermission.GROUP_READ,
    PosixFilePermission.OTHERS_READ
  )
val fileSystem = MemoryFileSystemBuilder.newLinux().setUmask(umask).build()
```

```
Caused by: java.nio.file.AccessDeniedException: /home
	at com.github.marschall.memoryfilesystem.MemoryEntryAttributes$MemoryPosixFileAttributeView.checkAccess(MemoryEntryAttributes.java:819)
	at com.github.marschall.memoryfilesystem.MemoryEntryAttributes.checkAccess(MemoryEntryAttributes.java:263)
	at com.github.marschall.memoryfilesystem.MemoryEntry.checkAccess(MemoryEntry.java:80)
	at com.github.marschall.memoryfilesystem.MemoryFileSystem$7.value(MemoryFileSystem.java:564)
	at com.github.marschall.memoryfilesystem.MemoryFileSystem$7.value(MemoryFileSystem.java:557)
	at com.github.marschall.memoryfilesystem.MemoryFileSystem$13.value(MemoryFileSystem.java:763)
	at com.github.marschall.memoryfilesystem.MemoryFileSystem.withLockDo(MemoryFileSystem.java:816)
	at com.github.marschall.memoryfilesystem.MemoryFileSystem.withWriteLockOnLastDo(MemoryFileSystem.java:756)
	at com.github.marschall.memoryfilesystem.MemoryFileSystem.withWriteLockOnLastDo(MemoryFileSystem.java:752)
	at com.github.marschall.memoryfilesystem.MemoryFileSystem.createFile(MemoryFileSystem.java:557)
	at com.github.marschall.memoryfilesystem.MemoryFileSystem.createDirectory(MemoryFileSystem.java:476)
	at com.github.marschall.memoryfilesystem.MemoryFileSystemProvider.createDirectory(MemoryFileSystemProvider.java:286)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at com.github.marschall.memoryfilesystem.MemoryFileSystemProvider.createNewFileSystem(MemoryFileSystemProvider.java:143)
	at com.github.marschall.memoryfilesystem.MemoryFileSystemProvider.newFileSystem(MemoryFileSystemProvider.java:75)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at com.github.marschall.memoryfilesystem.MemoryFileSystemBuilder.build(MemoryFileSystemBuilder.java:460)
	at com.github.marschall.memoryfilesystem.MemoryFileSystemBuilder.build(MemoryFileSystemBuilder.java:471)
```

**Comment by marschall** [comment]
```java
  val umask = util.EnumSet.of(
    PosixFilePermission.OWNER_WRITE,
    PosixFilePermission.OWNER_READ,
    PosixFilePermission.GROUP_READ,
    PosixFilePermission.OTHERS_READ
  )
```
The way [umask](https://en.wikipedia.org/wiki/Umask) works is that the bits that are set are disabled. This takes `OWNER_WRITE`, `OWNER_READ`, `GROUP_READ` and `OTHERS_READ` away from created files. Now when we create `/home/$USER` we don't have write permission on `/home`. Is this really what you want you do you want the inverse?
I checked the documentation on `MemoryFileSystemBuilder#setUmask` and it is horribly wrong and probably describes the behavior you expect. I'm sorry for this, this is from an old implantation where I was not aware how umask is supposed to work. As part of #44 I changed the behavior but forgot to update the documetnation.

**Comment by valery1707** [comment]
I run to same problem:
* `com.github.marschall.memoryfilesystem.MemoryFileSystemBuilder#setUmask` say: `Sets the permissions that will be applied to new files`
* but in create file procedure this permissions **removed** from all permissions: `com.github.marschall.memoryfilesystem.MemoryFileSystem#applyUmask`

**Comment by valery1707** [comment]
If problem in JavaDoc maybe I can make PR with JavaDoc fixes?

**Comment by marschall** [comment]
It's already fixed in #99, I can make a release I was simply waiting if @natansil agrees.

**Comment by marschall** [comment]
I just released 1.2.1 which changes the documentation to match the behavior. Let me know if this works for you.

**Comment by valery1707** [comment]
@marschall I already start using `umask` as `permissions what be removed from files after creating` - and it works for me.

JavaDoc is confusing - I spend ~30 minutes trying to find what was wrong with my code ...
Now it's ok for me - JavaDoc is synchronized with real behavior.

**Comment by marschall** [comment]
For completeness here's the new Javadoc:
https://static.javadoc.io/com.github.marschall/memoryfilesystem/1.2.1/com/github/marschall/memoryfilesystem/MemoryFileSystemBuilder.html#setUmask-java.util.Set-
